apiVersion: v1
kind: Service
metadata:
  name: test-service-cluster-ip
  namespace: services
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app: test-service