apiVersion: v1
kind: Service
metadata:
  name: test-service-nordport
  namespace: services
spec:
  type: NodePort
  selector:
    app: test-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30082