apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: services
  labels:
    app: test-service
spec:
  type: ClusterIP
  selector:
    app: test-service
  ports:
    - name: http
      port: 80
      targetPort: 80
