apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: gateway
data:
  kong.yaml: |
    _format_version: "3.0"
    _transform: true

    services:
      - name: test-service
        url: http://test-service.services.svc.cluster.local
        routes:
          - name: test-route
            paths:
              - /
            strip_path: false
            plugins:
              - name: jwt
                config:
                  secret_is_base64: false
                  key_claim_name: iss
                  maximum_expiration: 86400