apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: gateway
  labels:
    app: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      volumes:
        - name: kong-config-volume
          configMap:
            name: kong-config
      containers:
        - name: kong
          image: kong/kong-gateway:3.4
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_ADMIN_LISTEN
              value: "0.0.0.0:8001" 
            - name: KONG_DECLARATIVE_CONFIG
              value: "/opt/kong/kong.yaml"
            - name: KONG_PROXY_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_ADMIN_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_PROXY_ERROR_LOG
              value: "/dev/stderr"
            - name: KONG_ADMIN_ERROR_LOG
              value: "/dev/stderr"
            - name: KONG_LOG_LEVEL
              value: "info"
          volumeMounts:
            - name: kong-config-volume
              mountPath: /opt/kong/kong.yaml
              subPath: kong.yaml
          ports:
            - containerPort: 8000
