apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: gateway
data:
  nginx.conf: |
    worker_processes auto;
    events { worker_connections 1024; }

    http {
        include mime.types;
        sendfile on;
        keepalive_timeout 65;

        auth_jwt "Protected API";
        auth_jwt_key_request /_jwks;

        server {
            listen 80;

            location / {
                auth_jwt_claim_set iss "http://keycloak-internal.auth.svc.cluster.local:8080/realms/master";
                proxy_pass http://test-service.services.svc.cluster.local;
            }

            location = /_jwks {
                proxy_pass http://keycloak-internal.auth.svc.cluster.local:8080/realms/master/protocol/openid-connect/certs;
            }
        }
    }
