apiVersion: apps/v1
kind: Deployment
metadata:
  name: openresty-gateway
  namespace: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openresty-gateway
  template:
    metadata:
      labels:
        app: openresty-gateway
    spec:
      initContainers:
        - name: install-lua-modules
          image: openresty/openresty:alpine
          command:
            - /bin/sh
            - "-c"
            - |
              apk add --no-cache unzip git curl build-base luarocks
              luarocks install lua-resty-http
              luarocks install lua-resty-jwt
              luarocks install lua-resty-openidc
              mkdir -p /lua-modules
              cp -r /usr/local/share/lua/ /lua-modules
          volumeMounts:
            - name: lua-modules
              mountPath: /lua-modules
      containers:
        - name: openresty
          image: openresty/openresty:alpine
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: lua-modules
              mountPath: /usr/local/share/lua/
            - name: config-volume
              mountPath: /usr/local/openresty/nginx/conf/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: lua-modules
          emptyDir: {}
        - name: config-volume
          configMap:
            name: openresty-config
