apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: auth
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: bitnami/keycloak:26.1.2
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: adminUser
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: adminPassword
            - name: KEYCLOAK_DATABASE_HOST
              value: "postgres.auth.svc.cluster.local"
            - name: KEYCLOAK_DATABASE_PORT
              value: "5432"
            - name: KEYCLOAK_DATABASE_NAME
              value: postgres
            - name: KEYCLOAK_DATABASE_USER
              value: postgres
            - name: KEYCLOAK_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password
          ports:
            - containerPort: 8080
